name: iMomentum
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  geolocator: ^5.3.1
  http: ^0.12.0+4
  intl: ^0.16.0

  eva_icons_flutter: ^2.0.1
  font_awesome_flutter: ^8.8.1
  auto_size_text: ^2.1.0
  animated_text_kit: ^2.0.0
  flutter_spinkit: ^4.1.2
  google_fonts: ^1.0.0

  provider: ^4.1.2
  shared_preferences: '>=0.5.7+3 <2.0.0'
  share: '>=0.6.4+3 <2.0.0'
  url_launcher: ^5.4.11

  rxdart: ^0.24.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5

  table_calendar: ^2.2.3
  pie_chart: ^3.1.1

  cached_network_image: ^2.2.0+1 #image gallery
  photo_view: ^0.9.2 # zoom images
  firebase_storage: ^3.1.6 #for uploading photo
  image_picker: ^0.6.7+4 #for uploading photo

  tinycolor: ^1.0.2 #for count-down-cirlce
  assets_audio_player: 2.0.6+4

  flutter_staggered_grid_view: ^0.3.0
  flutter_slidable: ^0.5.4
  flushbar: ^1.10.4
  liquid_swipe: ^1.4.3 # for landing
  carousel_slider: ^2.2.1
  animations: ^1.1.2 #open container and routing
  liquid_progress_indicator: ^0.3.2 # in uploading your photo
  liquid_pull_to_refresh: ^2.0.0
  progress_dialog: ^1.2.4 # used in pick image

  path_provider: ^1.3.0
  flutter_local_notifications: ^1.4.4+4

#  easy_localization: ^2.3.2 # not apply yet
  flutter_localizations: # not apply yet
    sdk: flutter
#  flutter_cupertino_localizations: 1.0.1 # not apply yet

  image_cropper: ^1.3.1 #for uploading photo
  #  show_more_text_popup: ^0.2.0
  #  bubble: ^1.1.9+1
  #  popup_menu: ^1.0.5

  #  flare_splash_screen: ^3.0.1 # not apply yet
  #  flutter_blurhash: ^0.5.0 # not apply yet

  #  modal_progress_hud: ^0.1.3
  #  flutter_keyboard_visibility: ^3.2.1
  #  flutter_linkify: ^3.1.3
  #  auto_animated: ^2.1.0
  #  weather_icons: ^2.0.1
  #  extended_text_field: ^4.0.0
  #  speech_to_text: ^2.4.1
  #  speech_recognition: ^0.3.0+1
  #  permission_handler: ^5.0.1+1
  #  highlight_text: ^0.7.2
  #  avatar_glow: ^1.2.0
  #  weather: ^1.2.2
  #  curved_drawer: ^0.1.2
  #  flutter_zoom_drawer: ^1.0.4
  #  responsive_framework: ^0.0.4  #???
  #  sqflite: ^1.1.7
  #  webview_flutter: ^0.3.21
  #  firebase_helpers: ^0.1.8
  #  transparent_image: ^1.0.0
  #  qr_flutter: ^3.2.0  # not apply yet
  #  video_player: '0.10.11+2<2.0.0' # not apply yet
  #  indexed_list_view: ^1.0.9
  #  charts_flutter: ^0.9.0
  #  reorderables: ^0.3.2
  #  styled_widget: ^0.2.1+2 #???
  #  date_format: ^1.0.6  # format date
  #  wallpaper_manager: ^1.0.7
  #  modal_bottom_sheet: ^0.1.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
#  hive_generator: ^0.7.0+2
#  build_runner: ^1.8.0

#dependency_overrides:
##  quiver: 2.1.3
#  dartx: ^0.3.0

#  intl_translation: ^0.17.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/google_fonts/
#    - assets/sounds/speech_to_text_listening.m4r
#    - assets/sounds/speech_to_text_cancel.m4r
#    - assets/sounds/speech_to_text_stop.m4r

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977
  fonts:
    - family: MyFlutterAppIcon
      fonts:
        - asset: assets/fonts/custom_icons.ttf

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
