//list of tags scraped from 50 pages of unsplash.com/collections

class TagsList {
  static const tagsList = [
    'landscape',
    'Italy',
    'Greece',
    'Maldives',
    'Beach',
    'Sky',
    'Mountains',
    'Love',
    'Happiness',
    'New This Week',
    'Autumn',
    'Halloween',
    'political',
    'All Nations',
    'Collection #193: Unsplash',
    'technic',
    'Milkyway',
    'orange & red',
    'B&W',
    'Animals',
    'Collection #192: Unsplash',
    'The Colorful Collection',
    'SNEAKERS ',
    'Happy People',
    'Earth from Above',
    'Long Exposure',
    'Experimental',
    'blancs',
    'Portraits',
    'Trees, Mountains, Changing Leaves, Forest,  Nature, Pine',
    'Boho Chic',
    'Collection #191: Kevin Rose',
    'Unusually good',
    'Pugs',
    'Night Lights',
    'Yosemite',
    'Aerial Photos',
    'Blue',
    'Urbanismo',
    'Faces',
    'Christianity',
    'Collection #190: Unfold',
    'Split Screens',
    'Story telling',
    'Whitespace',
    'Powerful Women',
    "What I'm Holding",
    'The Curious Case of Benjamin Button',
    'People Smiling, Laughing, Happy',
    'Arcade',
    'Hot Air Balloons',
    'Put a Pin',
    'Feng Shui Inspired',
    'Perspective',
    'Ebony',
    'Collection #189: Jason Fried',
    'Collection #188: Unsplash',
    'Collection #187: Square',
    'Collection #186: Unsplash',
    'Insert Coin(s)',
    'Black & White',
    'Fog and Mist',
    'Collection #185: Unsplash',
    'Houseplant heaven',
    'The Colors of India',
    'Water Drop',
    'Adventure',
    'THE ROAD LESS TRAVELLED',
    '4th of July',
    'Collection #184: General Assembly',
    'Snow, Ice, and Winter',
    'Orange is the new black',
    'Collection #183: Unsplash',
    'Beautiful Shots From Above',
    'The Colour Purple',
    'Messages',
    'Expressive faces',
    'Pink',
    'Collection #182: Unsplash',
    'found typography',
    'Collection #181: Unsplash',
    "Pilgrim's Progress",
    'Pastel Pantone',
    'Eye Candy',
    'Field Trip Supply',
    'FIELD WORK',
    'Collection #180: Unsplash',
    'The Architecture Catwalk',
    'Friends',
    'HELLO DARKNESS, MY OLD FRIEND',
    'Clean',
    'Collection #179: Derek Sivers',
    'highkey',
    'Space',
    'Little Ones',
    'music',
    'sport',
    'Roads',
    'Sunglasses',
    'Plants',
    'Beasties',
    'Think Yellow',
    'Flat Lay Inspiration',
    'Collection #178: Flipboard',
    'Beauty + Make Up',
    'Home Decor + Design',
    'Neutrals',
    'Spring + Easter',
    'Red passion',
    'camping',
    'DiverseMen',
    'Inspiration Diverse',
    'colors',
    'Color Palette',
    'Flora',
    'Aerial',
    'Abstract Landscape/Nature',
    'Retro',
    'Unreal',
    'Chiseled',
    'Women',
    'Collection #177: Unsplash',
    'Great Outdoors',
    'Sky.',
    'Yoga | Ioga',
    'Moody Landscapes',
    'Neon',
    'Collection #176: Unsplash',
    'Direction & Time',
    'That Asian Life',
    'Flatlay: Tech Edition',
    'Church Culture',
    'Striking City Views',
    'Through a Rainy Window',
    'Human for scale.',
    'Clouds of Color',
    'Abandoned',
    'Warm and Muted Vol. 2',
    'Vibrant Blackouts (OLED)',
    'Spring',
    'Faded Adventures',
    'Street Life Photowalk',
    'abstract',
    'leafy',
    'Unsplash Top 25: Editor’s Choice Photos of 2018 |Q1',
    'Unsplash Top 25: Editor’s Choice Photographers of 2018 | Q1',
    'Unsplash Top 25: Most Viewed Photosof 2018 | Q1',
    'Unsplash Top 25: 25 Most Downloaded Photos of 2018 | Q1',
    'Unsplash Top 25: Most Downloaded Photographers of 2018 | Q1',
    'NEON',
    'Colour.',
    'Blurrrr',
    'Just Add Type | Vol. 2',
    'Travel the World',
    'Above the Trees',
    'TEXTURES / COLORS',
    'Turquoise + Pink',
    'architectural',
    'Mastering Monochrome ',
    'minimal',
    'Textures Of Earth',
    'Dappled Light',
    'Neutral',
    'Tidy!',
    'Hands',
    'Skateboard',
    'Collection #175: Earth',
    'Plant Life',
    'Backgrounds',
    'Street style',
    'Social History',
    'Portrait Orientation',
    "She's a Flower",
    'Collection #174: Typeform',
    'Globes and Maps',
    'Wavy',
    'home',
    'Bible',
    'City Lines',
    'Sports from Above',
    'Plant life',
    'Sun Sand Soul',
    "International Women's Day",
    'Winter Is Coming',
    'Create',
    'Sparkles',
    'Adventure & Action',
    'winter',
    'M I N I M A L I S M',
    "It's simple but very complex",
    'Restaurant & Cafe',
    'Yoga mindfulness',
    'Collection #173: Dribbble',
    'FLOOD',
    'Light Interiors',
    'Foggy Days',
    'Gentle Touch',
    'Beautiful Blur',
    "Valentine's Day",
    'Ode to Simplicity',
    'Mysterious landscapes',
    'Words to Inspire',
    'Good Morning!',
    'Go Explore and Never Look Back',
    'Road Trip #1: From Bavaria to Venice',
    'Facade',
    'The Minimalists Collection',
    'Miami & Flamingo feel',
    'Shades of White',
    '#SPACEDchallenge',
    'Collection #172: itsgreatoutthere',
    'Stuck in Time',
    "It's business time",
    'Italy | Italia',
    'Spring Tones ??',
    'Creative Spaces',
    'Workspaces',
    'Collection #171: FiftyThree',
    'SHADOW AND LIGHT',
    'healthy food',
    'Health & Fitness',
    'At Night',
    'Flowers with Black Background',
    'Collection #170: Remote Year',
    "Editor's Choice: 2017 Photos of the Year",
    'Top 100 Most Viewed Photos of 2017',
    'Top 100 Most Downloaded Photos of2017',
    'Adventures in Asia — Selects',
    'Collection #169: Unsplash',
    'Diverse Perspectives',
    'people',
    'InMotion',
    'Collection #168: Zedge',
    'Pastel & Pale',
    'Collection #167: Lonely Whale',
    'Moon and stars',
    'The Reading Man',
    'CHRISTMAS, SNOW AND WINTER',
    'Collection #166: Adobe Spark',
    'Wilderness Artifacts',
    'Write, Read, Note',
    'Flatlay',
    'Negative Space Flat Lays',
    'Tiny People in a Big World',
    'Think pink',
    'Pastel Tones',
    'DANCE THE NIGHT AWAY',
    'FESTIVE',
    'Shapes, Patterns & Textures',
    'People & Portraits',
    'AWASH IN COLOR',
    'Devices',
    'Flatlays',
    'Collection #165: Semplice',
    'Earth Tones',
    'Facial Recognition',
    'Reflections',
    "bird's eye kitchen ",
    'x2',
    'Textures',
    'Christmas',
    'People on Adventures',
    'Au Naturel',
    'Collection #164: Brevitē',
    'Technology',
    'Portraits',
    'PINKS, PURPLES, AND ALL THE HUES IN BETWEEN ',
    'Luminescence',
    'FROZEN IN TIME',
    'Collection #163: Vanguard World',
    'In Transit',
    'Collection #162: The Histographer',
    'Follow Me',
    'Hand It Over',
    'country flags ',
    'DUNES',
    'Typography',
    'Light of life',
    'Pet Lovers',
    'Coffee House',
    'Lights and Bulbs',
    'Urban Landscapes',
    'blooming life',
    'Pastel',
    'INTERIORS',
    'books, libraries, paper',
    'Storm and Storms Coming',
    'Anchored in the Storm - Epic Life',
    'Green energy - wind & solar',
    'Creatures',
    'Collection #161: Minimalism Life',
    'Texturizing ',
    'Digital Marketing',
    'DECO-HOME',
    'Office',
    'Aerial',
    'Soul Care',
    'Collection #160: imgix',
    'Collection #159: Lonely Planet',
    'Mobile Only 📱',
    'American Political',
    'In theAeroplane Over the Sea',
    'Star Seed',
    'A Closer Look',
    'Ants perspective',
    'conceptual',
    'Dark Bloom',
    'faceless',
    'Happy Birthday',
    'Collection #158: Product Hunt',
    'The People Of Earth',
    'Make Art',
    'Look Down',
    'STREET STYLE',
    'STYLED FOOD',
    'Home & Productivity',
    'Inside Voice (Interior Décor)',
    'Collection #157: Kodakit',
    'Wild',
    'Patterns',
    'The Grid',
    'Wildflowers',
    'Aerial/Drone Captures',
    'Hammer It Home (Houses)',
    'Abstract',
    'Spaced Out',
    'THE FLAT EARTH SOCIETY',
    'Data Communication',
    'Education',
    'Food Memories',
    'The Mystic',
    'Shopping',
    'Welcome to New York',
    'Animal Magnetism',
    'Collection #156: The Climate Reality Project',
    'Solar Eclipse 2017',
    'Express It',
    'Holiday Mood',
    'Illuminated',
    'Repeating image backdrops',
    'family',
    'Sport',
    "Let's Party!",
    'Girls Just Want To Have Fun',
    "The Back of Women's Heads",
    "Life's A Beach",
    'GoPro',
    'Water',
    'tiny',
    'Collection #155: Minimalism Life',
    'Blank Negative Space Background Flatlay Underlay ',
    'Earth Day',
    'Climate Action',
    'The Winter Issue',
    'The Art of Collaboration ',
    'Minimalismo / Minimalism',
    'Friendship',
    'Blog Header Images',
    'Pools',
    'School',
    'Hands on',
    'Shadows & Silhouettes',
    'For the love of caffeine',
    'Overhead',
    'SNEAKER',
    "I'm just a shadow",
    'Bulbs',
    'Stunning Scotland',
    'Blue',
    'Collection #154: Andre Benz',
    'FAIRY TALES AND CASTLES',
    'perfectly pale',
    'Jewelry',
    'covers',
    'Architecture, Buildings, Spaces',
    'Study ',
    'Work from Anywhere',
    'the great indoors',
    'Commerce Vs Architecture',
    'Urban Art',
    'Light Painting',
    'Fear',
    'Collection #153: Spotify',
    'Tempest',
    'Texture',
    'THEDEEP (BENEATH STILL WATERS)',
    'Urban Exploration',
    'Black & White',
    'Clean Backgrounds',
    'Collection #152: Inc.',
    'Flatlay Items',
    'Tilted',
    'Yellow + Grey',
    "Two's a Crowd",
    'Humanity',
    '50 SHADES OF PURPLE',
    'Creativity',
    'Morning.',
    'The Night Sky',
    'Wanderer',
    'Fashion Startups',
    'Inspiring Views (No People)',
    'Minimal.',
    'journey',
    'Celestial',
    'Collection #151: Ucraft',
    'That was Brutal',
    'Vintage',
    'Reflection & Introspection',
    'Photographers',
    'Holy cow, the colors!',
    "I'M GLAD TO SEE YOUR BACK",
    'Posters',
    'In the woods',
    'Couples',
    'Deep thinking',
    'Cool Background Ideas',
    'Urban Jungle',
    'Horses',
    'Red',
    'People',
    'Animals and Emotions',
    'Collection #150: Jeff Sheldon',
    'Drone Pictures',
    "Life's a Party",
    'Architectural lines',
    'Macros',
    'Drone Captures',
    'Textures',
    'Happy Feet',
    'The Stars Above My Head',
    'Monotone',
    'Portraotic'
  ];
}
